#!/usr/bin/env bash

set -e

RESOURSE_GROUP=rg-product-service-sand-ne-001
NAME=fa-products-service-sand-ne-001
SRC=./deployment.zip

az webapp deploy --resource-group $RESOURSE_GROUP \
  --name $NAME \
  --src-path $SRC
